---

- name: check if config file exists
  stat:
    path: ~/.docker/config.json
  register: config_file

- name: load current docker config
  slurp:
    src: ~/.docker/config.json
  register: docker_config
  when: config_file.stat.exists

- name: create config directory
  file:
    path: ~/.docker/
    state: directory
    mode: 0755

- name: save updated config
  copy:
    content: "{{ docker_config.content | default('e30=') | b64decode | from_json | combine({ '{{ docker_registry }}': 'ecr-login' }) | to_nice_json }}"
    dest: ~/.docker/config.json
