---
- name: copy docker-credential-ecr-login to /usr/bin
  copy:
    remote_src: yes
    src: /root/go/bin/docker-credential-ecr-login
    dest: /usr/bin/docker-credential-ecr-login
    mode: 0755
  become: yes

- name: check if config file exists
  stat:
    path: ~/.docker/config.json
  register: config_file

- name: load current docker config
  slurp:
    src: ~/.docker/config.json
  register: docker_config
  when: config_file.stat.exists

- name: create config directory
  file:
    path: ~/.docker/
    state: directory
    mode: 0755

- set_fact:
    patch: "{{ { 'credsStore': 'ecr-login' } }}"
  when: docker_registry is not defined

- set_fact:
    patch: "{{ { 'credHelpers': { docker_registry: 'ecr-login' } } }}"
  when: docker_registry is defined

- name: save updated config
  copy:
    content: "{{ docker_config.content | default('e30=') | b64decode | from_json | combine(patch) | to_nice_json }}"
    dest: ~/.docker/config.json
